export const DECLARATIONS = [
  {
    id: "683f846326fbb661f57b9f6f",
    picture: "http://placehold.it/32x32",
    comment:
      "pariatur reprehenderit incididunt ullamco amet fugiat amet ad et sit",
    status: "REJECTED",
    registered: "2025-02-28T05:26:49 -01:00",
    child: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Sawyer",
      lastName: "Marks",
      birthDate: "2025-04-18T06:12:34 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Santos",
      lastName: "Jacobs",
      email: "santosjacobs@slax.com",
      phone: "+1 (824) 531-2043",
      address: "141 Guider Avenue, Adamstown, Rhode Island, 397",
    },
    secondParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Graves",
      lastName: "Salazar",
      email: "gravessalazar@slax.com",
      phone: "+1 (862) 409-2959",
      address: "920 Berry Street, Baden, West Virginia, 4114",
    },
    company: {
      name: "Webiotic",
      address: "204 Herkimer Place, Warren, Maine, 4539",
    },
  },
  {
    id: "683f8463ebed839e5030f97d",
    picture: "http://placehold.it/32x32",
    comment: "ipsum non enim eu commodo sit ullamco nulla tempor labore",
    status: "ONGOING",
    registered: "2025-02-08T03:00:15 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Guzman",
      lastName: "Graves",
      birthDate: "2025-02-02T12:01:20 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Baird",
      lastName: "Greene",
      email: "bairdgreene@webiotic.com",
      phone: "+1 (987) 562-2246",
      address: "839 Junius Street, Tibbie, Michigan, 7784",
    },
    secondParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Moran",
      lastName: "Wilcox",
      email: "moranwilcox@webiotic.com",
      phone: "+1 (843) 554-3138",
      address: "749 Forbell Street, Comptche, Tennessee, 2805",
    },
    company: {
      name: "Comtest",
      address: "538 Centre Street, Greenbush, Arizona, 4101",
    },
  },
  {
    id: "683f8463dea6856a0a82662f",
    picture: "http://placehold.it/32x32",
    comment: "laborum qui culpa est in aliqua nostrud veniam ipsum velit",
    status: "NEW",
    registered: "2025-04-14T08:48:17 -01:00",
    child: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Angeline",
      lastName: "Galloway",
      birthDate: "2025-03-22T06:59:38 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Darla",
      lastName: "Howell",
      email: "darlahowell@comtest.com",
      phone: "+1 (889) 431-2669",
      address: "679 Winthrop Street, Sussex, Palau, 729",
    },
    secondParent: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Marjorie",
      lastName: "Mays",
      email: "marjoriemays@comtest.com",
      phone: "+1 (825) 553-2455",
      address: "418 Tennis Court, Cassel, Indiana, 4936",
    },
    company: {
      name: "Printspan",
      address: "455 Newport Street, Mooresburg, Iowa, 5004",
    },
  },
  {
    id: "683f846369f6a9a80bf15138",
    picture: "http://placehold.it/32x32",
    comment: "eu tempor officia do enim id voluptate elit adipisicing aute",
    status: "NEW",
    registered: "2025-01-31T08:53:29 -01:00",
    child: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Katrina",
      lastName: "Mullins",
      birthDate: "2025-04-03T06:11:05 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Fields",
      lastName: "Lynn",
      email: "fieldslynn@printspan.com",
      phone: "+1 (908) 509-2698",
      address: "517 Jackson Place, Coyote, Louisiana, 8661",
    },
    secondParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Mills",
      lastName: "Kline",
      email: "millskline@printspan.com",
      phone: "+1 (933) 439-3111",
      address: "323 Montana Place, Westerville, Virgin Islands, 3158",
    },
    company: {
      name: "Hydrocom",
      address: "735 Hull Street, Faywood, Wisconsin, 1473",
    },
  },
  {
    id: "683f8463aa274911d3a5a342",
    picture: "http://placehold.it/32x32",
    comment:
      "mollit exercitation nostrud est officia qui pariatur aute labore anim",
    status: "ONGOING",
    registered: "2025-01-13T02:31:26 -01:00",
    child: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Glenn",
      lastName: "Freeman",
      birthDate: "2025-03-06T10:14:11 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Johnson",
      lastName: "Ramos",
      email: "johnsonramos@hydrocom.com",
      phone: "+1 (974) 511-3227",
      address: "841 Taylor Street, Waverly, Delaware, 3439",
    },
    secondParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Jefferson",
      lastName: "Knight",
      email: "jeffersonknight@hydrocom.com",
      phone: "+1 (830) 600-3155",
      address: "248 Brigham Street, Dante, Utah, 1230",
    },
    company: {
      name: "Comtent",
      address: "452 Pitkin Avenue, Harleigh, Nebraska, 5993",
    },
  },
  {
    id: "683f84637694391a15a80e8e",
    picture: "http://placehold.it/32x32",
    comment:
      "ullamco culpa laboris id reprehenderit cupidatat enim ut deserunt ullamco",
    status: "VALIDATED",
    registered: "2025-03-01T02:51:47 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Collier",
      lastName: "Murphy",
      birthDate: "2025-02-23T11:06:19 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Cora",
      lastName: "Bailey",
      email: "corabailey@comtent.com",
      phone: "+1 (818) 454-2093",
      address: "332 Locust Avenue, Longbranch, Northern Mariana Islands, 7583",
    },
    secondParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Barrett",
      lastName: "Dawson",
      email: "barrettdawson@comtent.com",
      phone: "+1 (915) 519-3301",
      address: "327 Bayview Avenue, Temperanceville, Mississippi, 7755",
    },
    company: {
      name: "Tropolis",
      address: "206 Flatlands Avenue, Devon, North Carolina, 3902",
    },
  },
  {
    id: "683f8463bad2ba1133ef16dc",
    picture: "http://placehold.it/32x32",
    comment: "ullamco cupidatat quis culpa duis ea id sunt irure laborum",
    status: "NEW",
    registered: "2025-04-17T02:30:15 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Snow",
      lastName: "Curtis",
      birthDate: "2025-05-02T05:24:39 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Mavis",
      lastName: "Acosta",
      email: "mavisacosta@tropolis.com",
      phone: "+1 (845) 480-2154",
      address: "518 Jewel Street, Conestoga, Alabama, 9230",
    },
    secondParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Allie",
      lastName: "Wilkerson",
      email: "alliewilkerson@tropolis.com",
      phone: "+1 (815) 507-3756",
      address: "436 Elm Avenue, Martinez, Illinois, 2638",
    },
    company: {
      name: "Conjurica",
      address: "731 Sedgwick Place, Welch, Vermont, 8138",
    },
  },
  {
    id: "683f846328e611899046eec7",
    picture: "http://placehold.it/32x32",
    comment:
      "excepteur ex excepteur adipisicing sit sit labore exercitation nulla esse",
    status: "VALIDATED",
    registered: "2025-04-19T10:13:56 -01:00",
    child: {
      gender: "female",
      eyeColor: "green",
      firstName: "Randi",
      lastName: "Baldwin",
      birthDate: "2025-01-04T08:25:22 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Nicole",
      lastName: "Hogan",
      email: "nicolehogan@conjurica.com",
      phone: "+1 (903) 525-2031",
      address: "387 Conway Street, Takilma, Connecticut, 4002",
    },
    secondParent: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Daisy",
      lastName: "Vega",
      email: "daisyvega@conjurica.com",
      phone: "+1 (936) 501-3634",
      address: "819 Beekman Place, Felt, South Dakota, 8555",
    },
    company: {
      name: "Mantro",
      address: "235 Sapphire Street, Hoehne, Wyoming, 2270",
    },
  },
  {
    id: "683f846357adafdda57e7340",
    picture: "http://placehold.it/32x32",
    comment: "ipsum et anim Lorem laborum occaecat consequat nulla cillum ut",
    status: "VALIDATED",
    registered: "2025-03-07T03:54:06 -01:00",
    child: {
      gender: "female",
      eyeColor: "green",
      firstName: "Rosetta",
      lastName: "House",
      birthDate: "2025-01-20T12:30:02 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Hancock",
      lastName: "Fernandez",
      email: "hancockfernandez@mantro.com",
      phone: "+1 (909) 435-3807",
      address: "753 Ashland Place, Bainbridge, Colorado, 4827",
    },
    secondParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Bethany",
      lastName: "Sherman",
      email: "bethanysherman@mantro.com",
      phone: "+1 (890) 558-2359",
      address: "490 Highland Avenue, Katonah, Oregon, 1705",
    },
    company: {
      name: "Wazzu",
      address: "646 Balfour Place, Dotsero, New Mexico, 4386",
    },
  },
  {
    id: "683f846371db55200a4584be",
    picture: "http://placehold.it/32x32",
    comment:
      "nisi ad aliquip deserunt ullamco voluptate amet adipisicing nulla officia",
    status: "ONGOING",
    registered: "2025-03-31T08:40:06 -01:00",
    child: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Simon",
      lastName: "Golden",
      birthDate: "2025-01-08T08:01:50 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Kirby",
      lastName: "Gordon",
      email: "kirbygordon@wazzu.com",
      phone: "+1 (971) 472-3298",
      address: "440 Fiske Place, Wilsonia, Texas, 4889",
    },
    secondParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Amparo",
      lastName: "Calderon",
      email: "amparocalderon@wazzu.com",
      phone: "+1 (994) 543-2276",
      address: "629 Elizabeth Place, Cobbtown, Virginia, 1664",
    },
    company: {
      name: "Paprikut",
      address: "583 Hinckley Place, Gerton, Puerto Rico, 8000",
    },
  },
  {
    id: "683f8463d47d2f3b0310beb2",
    picture: "http://placehold.it/32x32",
    comment: "nostrud velit mollit enim do qui magna exercitation in ipsum",
    status: "REJECTED",
    registered: "2025-05-31T10:00:38 -01:00",
    child: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Austin",
      lastName: "Daugherty",
      birthDate: "2025-03-16T05:48:56 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Pratt",
      lastName: "Rivers",
      email: "prattrivers@paprikut.com",
      phone: "+1 (979) 489-2298",
      address: "284 Homecrest Avenue, Itmann, Georgia, 1690",
    },
    secondParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Guy",
      lastName: "Oneill",
      email: "guyoneill@paprikut.com",
      phone: "+1 (817) 492-2899",
      address: "495 Amersfort Place, Benson, Missouri, 4669",
    },
    company: {
      name: "Buzzopia",
      address: "293 Garnet Street, Nettie, Kentucky, 5914",
    },
  },
  {
    id: "683f84631086b197d0584bf4",
    picture: "http://placehold.it/32x32",
    comment:
      "mollit nisi deserunt occaecat eiusmod ullamco ex qui ipsum fugiat",
    status: "NEW",
    registered: "2025-02-11T12:36:25 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Woodard",
      lastName: "Price",
      birthDate: "2025-02-18T07:26:15 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Pearlie",
      lastName: "Green",
      email: "pearliegreen@buzzopia.com",
      phone: "+1 (897) 453-3911",
      address: "640 Agate Court, Mulberry, New Jersey, 9664",
    },
    secondParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Vanessa",
      lastName: "Frye",
      email: "vanessafrye@buzzopia.com",
      phone: "+1 (906) 584-3610",
      address: "398 Lloyd Street, Chase, Kansas, 8118",
    },
    company: {
      name: "Flotonic",
      address: "921 Keen Court, Brandermill, District Of Columbia, 2057",
    },
  },
  {
    id: "683f8463080da03efef34c1c",
    picture: "http://placehold.it/32x32",
    comment:
      "nisi in officia magna reprehenderit adipisicing id veniam aliquip velit",
    status: "VALIDATED",
    registered: "2025-02-05T09:01:29 -01:00",
    child: {
      gender: "female",
      eyeColor: "green",
      firstName: "Michelle",
      lastName: "Lara",
      birthDate: "2025-03-26T02:09:36 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Maryann",
      lastName: "Rios",
      email: "maryannrios@flotonic.com",
      phone: "+1 (948) 445-3855",
      address: "696 Hoyt Street, Yardville, Alaska, 6520",
    },
    secondParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Rebecca",
      lastName: "Terrell",
      email: "rebeccaterrell@flotonic.com",
      phone: "+1 (991) 493-2627",
      address: "913 Norfolk Street, Curtice, New York, 2434",
    },
    company: {
      name: "Farmex",
      address: "110 Erasmus Street, Veyo, Washington, 6643",
    },
  },
  {
    id: "683f846380a6efd47a99bfa5",
    picture: "http://placehold.it/32x32",
    comment:
      "amet mollit adipisicing occaecat ex non consectetur labore aute nostrud",
    status: "ONGOING",
    registered: "2025-04-16T10:11:41 -01:00",
    child: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Raquel",
      lastName: "Wooten",
      birthDate: "2025-04-07T11:27:12 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Ladonna",
      lastName: "Carter",
      email: "ladonnacarter@farmex.com",
      phone: "+1 (877) 551-2881",
      address: "675 Lloyd Court, Norfolk, Arkansas, 3889",
    },
    secondParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Garrett",
      lastName: "Rowe",
      email: "garrettrowe@farmex.com",
      phone: "+1 (811) 521-3823",
      address:
        "816 Meserole Avenue, Templeton, Federated States Of Micronesia, 7585",
    },
    company: {
      name: "Kiggle",
      address: "803 Bridge Street, Cumminsville, Minnesota, 4768",
    },
  },
  {
    id: "683f84635d75181d422cd54f",
    picture: "http://placehold.it/32x32",
    comment:
      "duis exercitation Lorem laboris proident aliquip magna ut in reprehenderit",
    status: "ONGOING",
    registered: "2025-03-29T08:05:08 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Osborne",
      lastName: "Frost",
      birthDate: "2025-02-19T10:05:12 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Robinson",
      lastName: "Glenn",
      email: "robinsonglenn@kiggle.com",
      phone: "+1 (819) 493-3018",
      address: "157 Glen Street, Nanafalia, Marshall Islands, 5922",
    },
    secondParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Dejesus",
      lastName: "Odom",
      email: "dejesusodom@kiggle.com",
      phone: "+1 (812) 429-2059",
      address: "376 Kane Street, Brooktrails, Pennsylvania, 6666",
    },
    company: {
      name: "Aclima",
      address: "688 Suydam Place, Johnsonburg, California, 8898",
    },
  },
  {
    id: "683f8463b3af66ed78ea86d3",
    picture: "http://placehold.it/32x32",
    comment:
      "commodo irure minim officia Lorem magna nulla excepteur aute incididunt",
    status: "VALIDATED",
    registered: "2025-06-02T06:36:41 -01:00",
    child: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Deanna",
      lastName: "Herrera",
      birthDate: "2025-04-24T06:05:14 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Bird",
      lastName: "Langley",
      email: "birdlangley@aclima.com",
      phone: "+1 (806) 528-2782",
      address: "475 Locust Street, Wyoming, Hawaii, 4922",
    },
    secondParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Annmarie",
      lastName: "Sims",
      email: "annmariesims@aclima.com",
      phone: "+1 (951) 476-3181",
      address: "616 Harwood Place, Aberdeen, Ohio, 9478",
    },
    company: {
      name: "Premiant",
      address: "609 Coventry Road, Ventress, Idaho, 6457",
    },
  },
  {
    id: "683f8463b2e9d2e0ff92a128",
    picture: "http://placehold.it/32x32",
    comment: "occaecat dolore sunt aliqua enim non tempor velit adipisicing id",
    status: "NEW",
    registered: "2025-01-17T06:12:48 -01:00",
    child: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Bridgette",
      lastName: "Randolph",
      birthDate: "2025-05-21T08:14:14 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Hunter",
      lastName: "Hebert",
      email: "hunterhebert@premiant.com",
      phone: "+1 (848) 439-2895",
      address: "235 Harbor Lane, Alafaya, Florida, 8285",
    },
    secondParent: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Neal",
      lastName: "Fox",
      email: "nealfox@premiant.com",
      phone: "+1 (950) 526-3540",
      address: "126 Harden Street, Farmers, Nevada, 8227",
    },
    company: {
      name: "Zedalis",
      address: "436 Moffat Street, Bancroft, Guam, 9554",
    },
  },
  {
    id: "683f8463268c42212c195b7e",
    picture: "http://placehold.it/32x32",
    comment: "id consectetur sit id anim sit veniam ex adipisicing enim",
    status: "REJECTED",
    registered: "2025-01-08T04:17:23 -01:00",
    child: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Jamie",
      lastName: "Rosa",
      birthDate: "2025-03-23T04:41:24 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Jodie",
      lastName: "Strong",
      email: "jodiestrong@zedalis.com",
      phone: "+1 (911) 527-2771",
      address: "953 Debevoise Avenue, Cornucopia, South Carolina, 766",
    },
    secondParent: {
      gender: "female",
      eyeColor: "green",
      firstName: "Burks",
      lastName: "Cabrera",
      email: "burkscabrera@zedalis.com",
      phone: "+1 (919) 552-2254",
      address: "937 Scott Avenue, Omar, North Dakota, 3797",
    },
    company: {
      name: "Zerology",
      address: "402 Lenox Road, Orick, Montana, 3338",
    },
  },
  {
    id: "683f8463b59d51cfe8a19369",
    picture: "http://placehold.it/32x32",
    comment:
      "et elit exercitation proident veniam sint deserunt nulla elit quis",
    status: "NEW",
    registered: "2025-03-23T04:06:24 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Reilly",
      lastName: "Battle",
      birthDate: "2025-01-22T07:12:46 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Penelope",
      lastName: "Dale",
      email: "penelopedale@zerology.com",
      phone: "+1 (989) 506-3192",
      address: "356 Ellery Street, Allison, Massachusetts, 2336",
    },
    secondParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Saunders",
      lastName: "Davenport",
      email: "saundersdavenport@zerology.com",
      phone: "+1 (935) 516-3298",
      address: "984 Bush Street, Rockhill, New Hampshire, 3210",
    },
    company: {
      name: "Crustatia",
      address: "955 Dunham Place, Sparkill, Maryland, 5111",
    },
  },
  {
    id: "683f8463afca8859231763f2",
    picture: "http://placehold.it/32x32",
    comment:
      "officia laboris nulla consequat tempor aute incididunt amet Lorem amet",
    status: "NEW",
    registered: "2025-02-16T01:21:50 -01:00",
    child: {
      gender: "male",
      eyeColor: "brown",
      firstName: "Lucinda",
      lastName: "Skinner",
      birthDate: "2025-05-16T10:12:46 -01:00",
    },
    firstParent: {
      gender: "female",
      eyeColor: "blue",
      firstName: "Margery",
      lastName: "Mann",
      email: "margerymann@crustatia.com",
      phone: "+1 (816) 450-3304",
      address: "380 Woodside Avenue, Rew, American Samoa, 8181",
    },
    secondParent: {
      gender: "female",
      eyeColor: "brown",
      firstName: "Trudy",
      lastName: "Mccormick",
      email: "trudymccormick@crustatia.com",
      phone: "+1 (984) 582-2267",
      address: "702 Kossuth Place, Bladensburg, Rhode Island, 7766",
    },
    company: {
      name: "Glasstep",
      address: "393 Saratoga Avenue, Fontanelle, West Virginia, 5224",
    },
  },
  {
    id: "683f8463f08b15407b4276e9",
    picture: "http://placehold.it/32x32",
    comment: "ut non aliquip ullamco deserunt aliquip duis laborum do pariatur",
    status: "VALIDATED",
    registered: "2025-04-03T03:56:22 -01:00",
    child: {
      gender: "female",
      eyeColor: "green",
      firstName: "Estrada",
      lastName: "English",
      birthDate: "2025-04-19T07:35:13 -01:00",
    },
    firstParent: {
      gender: "male",
      eyeColor: "blue",
      firstName: "Casey",
      lastName: "Lester",
      email: "caseylester@glasstep.com",
      phone: "+1 (856) 593-3704",
      address: "168 Bayard Street, Foxworth, Maine, 9809",
    },
    secondParent: {
      gender: "male",
      eyeColor: "green",
      firstName: "Carol",
      lastName: "Wallace",
      email: "carolwallace@glasstep.com",
      phone: "+1 (960) 430-3165",
      address: "625 Barwell Terrace, Kirk, Michigan, 7107",
    },
    company: {
      name: "Mondicil",
      address: "509 Hamilton Avenue, Orason, Tennessee, 2880",
    },
  },
];

export const getDeclarationStatusColor = (status: string) => {
  switch (status.toUpperCase()) {
    case "ONGOING":
      return {
        color: "text-amber-600",
        label: "In Progress",
      };
    case "VALIDATED":
      return {
        color: "text-green-600",
        label: "Validated",
      };
    case "REJECTED":
      return {
        color: "text-red-600",
        label: "Rejected",
      };
    default:
      return {
        color: "",
        label: "Submited",
      };
  }
};
